version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=triumph_db

  frontend:
    build:
      context: ./frontend-react
      dockerfile: Dockerfile
    volumes:
      - ./frontend-react:/app
      - /app/node_modules
    ports:
      - '8080:80'

  db:
    image: postgres:13-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=triumph_db
    ports:
      - '5432:5432'

volumes:
  db-data:
